# Generated by Django 6.1.1 on 2026-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_complement',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='BR', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_neighborhood',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(default='', max_length=180),
        ),
    ]
