# Generated by Django 6.1.1 on 2026-09-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=40)),
                ('event_id', models.CharField(blank=True, default='', max_length=160)),
                ('event_type', models.CharField(blank=True, default='', max_length=80)),
                ('external_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('external_status', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orders.payment')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['external_status', 'created_at'], name='payment_event_status_idx'), models.Index(fields=['external_payment_id'], name='payment_event_external_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_id', ''), _negated=True), fields=('provider', 'event_id'), name='unique_provider_payment_event')],
            },
        ),
    ]
