# Generated by Django 6.1.1 on 2026-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_idempotency_key_payment_provider_data_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('order',), name='unique_paid_payment_per_order'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order', 'method', 'provider'), name='unique_pending_payment_attempt'),
        ),
    ]
