# Generated by Django 6.1.1 on 2026-09-24 15:53

import apps.catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_initial_colors_and_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp', 'gif')), apps.catalog.validators.validate_product_image_size]),
        ),
    ]
